apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-clone-lighthouse
spec:
  type: git
  params:
    - name: revision
      value: modify-0.0.748
    - name: url
      value: https://github.com/yyunk/lighthouse.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: lighthouse-image-out
spec:
  type: image
  params:
    - name: url
      value: 213.146.155.118:5500/lighthouse