FROM ubuntu:18.04
RUN  apt-get update &&  apt install openssh-client -y
COPY lighthouse-jx-controller /lighthouse-jx-controller
RUN mkdir /jxhome
ENV JX_HOME /jxhome
ENTRYPOINT ["/lighthouse-jx-controller"]
