apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-kaniko-loop
spec:
  resources:
    - name: kaniko-pipeline-input
      type: git
  tasks:
    - name: step1
      taskRef:
        name: task-tekton
      params:
        - name: dockerRegistry
          value: 213.146.155.118:5500
        - name: containerImageTag
          value: test-loop
      resources:
        inputs:
          - name: task-input-kaniko
            resource: kaniko-pipeline-input