apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-lighthouse-loop
spec:
  resources:
    - name: lighthouse-pipeline-input-1
      type: git
    - name: lighthouse-pipeline-out-1
      type: image
  tasks:
    - name: step1
      taskRef:
        name: task-lighthouse-loop
      params:
        - name: dockerRegistry
          value: 213.146.155.118:5500
        - name: containerImageTag
          value: test-loop
      resources:
        inputs:
          - name: task-input-lighthouse-1
            resource: lighthouse-pipeline-input-1
        outputs:
          - name: task-out-lighthouse-1
            resource: lighthouse-pipeline-out-1