apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-tekton-loop
spec:
  resources:
    - name: tekton-pipeline-input-1
      type: git
  tasks:
    - name: step1
      taskRef:
        name: task-tekton
      params:
        - name: dockerRegistry
          value: 213.146.155.118:5500
        - name: containerImageTag
          value: test-loop
      resources:
        inputs:
          - name: task-input-tekton
            resource: tekton-pipeline-input-1