apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-hello-pipeline
spec:
  resources:
    - name: pipeline-input-1
      type: git
    - name: pipeline-out-1
      type: image
  tasks:
    - name: step1
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: task-input-1
            resource: pipeline-input-1
        outputs:
          - name: task-out-1
            resource: pipeline-out-1

