apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-clone-hello-in-1
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/yyk757/test-hello
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: build-and-push-image-out-1
spec:
  type: image
  params:
    - name: url
      value: 213.146.155.118:5000/test-hello:v1

