apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-tekton-CD
spec:
  resources:
    inputs:
      - name: task-input-tekton
        type: git
  steps:
    - name: deploy-tekton 
      image: kubectl-helm:v1
      volumeMounts:
        - name: kube-config
          mountPath: /root/.kube
      script: |
        #!/usr/bin/env bash
        git clone https://github.com/yyunk/tekton.git -b modify-3.2-CICD
        cd tekton/
        helm upgrade tekton5 tekton  --install --namespace test5 --values myvalues.yaml
  volumes:
    - name: kube-config
      hostPath:
        path: /home/ubuntu/.kube
