apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-lighthouse-loop
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: pipeline-lighthouse-loop
  resources:
    - name: lighthouse-pipeline-input-1
      resourceRef:
        name: git-clone-lighthouse
    - name: lighthouse-pipeline-out-1
      resourceRef:
        name: lighthouse-image-out